### ISSUE TITLE
Android - Signature request: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by xactant** [WalletConnect/WalletConnectUnity#19]
Deep link sent and wallet opens. 
- User accepts connection
- App receives connection response and sends signature request: 
```
    string response = await walletConnect.Session.EthPersonalSign(address, "Moralis Authentication");
```
- Exception thrown.

Log:
---------
2021-11-06 16:02:25.994 10738-10767/com.MoralisIO.LogInTest I/Unity: Sending sign request for 0x5819ff18c1c1f42d1ac90ffecc25990431690198 ...
    UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
    UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
    UnityEngine.Logger:Log (UnityEngine.LogType,object)
    UnityEngine.Debug:Log (object)
    MainMenuScript/<WalletConnectHandler>d__11:MoveNext () (at C:/projects/moralis/unity/LogInTest/Assets/Scripts/MainMenuScript.cs:90)
    System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start<MainMenuScript/<WalletConnectHandler>d__11> (MainMenuScript/<WalletConnectHandler>d__11&)
    MainMenuScript:WalletConnectHandler (WalletConnectSharp.Core.Models.WCSessionData)
    UnityEngine.Events.InvokableCall`1<WalletConnectSharp.Core.Models.WCSessionData>:Invoke (WalletConnectSharp.Core.Models.WCSessionData) (at /Users/bokken/buildslave/unity/build/Runtime/Export/UnityEvent/UnityEvent.cs:221)
    UnityEngine.Events.UnityEvent`1<WalletConnectSharp.
2021-11-06 16:02:26.125 10738-10738/com.MoralisIO.LogInTest I/Unity: onPause
2021-11-06 16:02:26.126 10738-10767/com.MoralisIO.LogInTest I/Unity: [WebSocket] Pausing
    UnityEngine.StackTraceUtility:ExtractStackTrace () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/StackTrace.cs:37)
    UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
    UnityEngine.Logger:Log (UnityEngine.LogType,object)
    UnityEngine.Debug:Log (object)
    WalletConnectSharp.Unity.Network.NativeWebSocketTransport/<OnApplicationPause>d__34:MoveNext () (at C:/projects/moralis/unity/LogInTest/Assets/Scripts/WalletConnectSharp.Unity/Network/NativeWebSocketTransport.cs:271)
    UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
2021-11-06 16:02:26.145 10738-10767/com.MoralisIO.LogInTest D/Unity: Vulkan PSO: Pipeline cache has not changed skipping save handle[c102d160]
2021-11-06 16:02:26.145 10738-10767/com.MoralisIO.LogInTest D/lisIO.LogInTes: PlayerBase::stop() from IPlayer
2021-11-06 16:02:26.145 10738-10767/com.MoralisIO.LogInTest D/AudioTrack: stop(690): called with 285504 frames delivered
2021-11-06 16:02:26.148 10738-10767/com.MoralisIO.LogInTest D/Unity: Sensor :        Accelerometer ( 1) ; 0.004786 / 0.00s ; LSM6DSR Accelerometer / STMicro 
2021-11-06 16:02:26.164 10738-10738/com.MoralisIO.LogInTest I/Unity: windowFocusChanged: false
2021-11-06 16:02:32.606 10738-10738/com.MoralisIO.LogInTest D/Unity: PersistentUnitySurface.preserveContent: android.view.SurfaceView{8e04096 VFE...... .F....I. 0,0-1080,2280 #7f010000 app:id/unitySurfaceView aid=1073741824}
2021-11-06 16:02:32.606 10738-10738/com.MoralisIO.LogInTest D/Unity: Last resumed Activity is the Unity activity, no need to preserve SurfaceView content
2021-11-06 16:02:32.611 10738-10767/com.MoralisIO.LogInTest D/Unity: SetWindow 0 0x0
2021-11-06 16:02:32.617 10738-10824/com.MoralisIO.LogInTest I/SwappyDisplayManager: Terminating looper thread
2021-11-06 16:02:37.140 10738-10763/com.MoralisIO.LogInTest W/MessageQueue: Handler (android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate) {955fbc0} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate) {955fbc0} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.sendDisplayEvent(DisplayManagerGlobal.java:722)
        at android.hardware.display.DisplayManagerGlobal.handleDisplayEvent(DisplayManagerGlobal.java:351)
        at android.hardware.display.DisplayManagerGlobal.access$200(DisplayManagerGlobal.java:55)
        at android.hardware.display.DisplayManagerGlobal$DisplayManagerCallback.onDisplayEvent(DisplayManagerGlobal.java:708)
        at android.hardware.display.IDisplayManagerCallback$Stub.onTransact(IDisplayManagerCallback.java:84)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)

**Comment by ecp4224** [comment]
I'm not able to reproduce this in the current #21 PR. Could I get more context about how you're calling this function?

**Comment by gigajuwels** [comment]
@xactant is this a custom android project export from unity?

**Comment by xactant** [comment]
This issue can be closed. An update released by Eddie (ecp4224) on Dec 3 fixed this. I was able to use it in late December, sorry i did not get back sooner.

**Comment by gigajuwels** [comment]
closed due to v1 depreciation & resolved from above comment
